
#
# This LookML file was generated by AtScale on 2024-02-05T16:20:25.995455Z
#
# AtScale engine version: 2023.3.0.12549
# AtScale DesignCenter version: 2023.3.0.21052
# AtScale version: 2023.3.0.6480
# Organization: default
# Project: 10TB - GBQ

connection: "looker_sb_gbq"
label: "10TB - GBQ"


include: "/views/10TB_-_GBQ/10TB_-_GBQ.view.lkml"


explore: 10TB___GBQ {
  label: "10TB - GBQ"
}

