
#
# This LookML file was generated by AtScale on 2024-05-24T19:24:38.651475498Z
#
# AtScale engine version: 2024.1.0.12792
# AtScale DesignCenter version: 2024.1.0.21169
# AtScale version: 2024.1.0.6834
# Organization: default
# Project: 10TB - GBQ

connection: "looker_sb_gbq"
label: "10TB - GBQ"


include: "/views/10TB_-_GBQ/10TB_-_GBQ.view.lkml"


explore: 10TB___GBQ {
  label: "10TB - GBQ"
}

