
#
# This LookML file was generated by AtScale on 2024-12-12T14:48:40.010091127Z
#
# AtScale engine version: 2024.2.6.13070
# AtScale DesignCenter version: 2024.2.6.21274
# AtScale version: 2024.2.6.7160
# Organization: default
# Project: 10TB - GBQ

connection: "looker_sb_gbq"
label: "10TB - GBQ"


include: "/views/10TB_-_GBQ/10TB_-_GBQ.view.lkml"


explore: 10TB___GBQ {
  label: "10TB - GBQ"
}

